name: Terraform AWS Lambda Execution

on:
  push:
    branches:
      - mainx  # Change this to your main branch name if different
  repository_dispatch:
    types: [trigger-tf-apply]
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.0

    - name: Install Terragrunt
      run: |
        TG_VERSION=0.55.0
        curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64 -o terragrunt
        chmod +x terragrunt
        sudo mv terragrunt /usr/local/bin/
   
    - name: Verify versions
      run: |
        terraform -version
        terragrunt --version
   
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: AWS
      shell: bash
      run: |
        pwd
        aws s3 ls
        env

    - name: Terragrunt Plan
      run: terragrunt run-all plan --terragrunt-non-interactive
      working-directory: environment

    - name: Terraform Apply or Destroy
      run: |
        if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
          terragrunt run-all apply --terragrunt-non-interactive
        elif [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
          terragrunt run-all destroy --terragrunt-non-interactive
        fi
      working-directory: environment

    - name: Archive Terraform Plan
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: tfplan
        path: '**'
